name: CD_UAT

on:
  workflow_run:
    workflows: ["Node.js CI"]
    branches: [main]
    types: [completed]
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow passed'